[package]
name = "archiver"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
workerpool = "1.2.1"
byteorder = "1.5.0"
crypto = { path = "../crypto" }
compressor = { path = "../compressor" }
